name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Lint
        env:
          CI: true
        run: |
          npm ci
          npm run lint
